### ISSUE TITLE
validate_length and empty strings

### ISSUE THREAD

**Issue by frekw** [sticksnleaves/justify#9]
Hi!

`validate_length` currently accepts the empty string for `is` as well as `min`. This seems like incorrect behaviour to me, since an empty value and the presence of a value isn't the same. It also makes it more or less impossible to validate that an optional value (e.g can't use `validate_required`) isn't the empty string.

**Comment by pierresomos** [comment]
yes. There is a bug

````
iex(1)> Justify.validate_length(%{"oba" => ""}, "oba", min: 3)
%Justify.Dataset{data: %{"oba" => ""}, errors: [], valid?: true}
````
I will try to fix it as soon as possible

**Comment by anthonator** [comment]
When you say an "optional value" you mean it's not required (can be `nil`) but it also can't be blank? I'm not sure I understand how that's an optional value.

**Comment by frekw** [comment]
I'm validating a config. It has an optional key (`project`) that if it exists, must not be blank (i.e a min length of 1). But providing it is completely optional.

So,

```
# valid
%{}

# valid
%{
  project: "foo"
}

# invalid
%{
  project: ""
}
```

I think the same would be true for many REST API implementations, but I making the distinction in HTML forms is tricker.

**Comment by anthonator** [comment]
What about something like this?

```
def validate_project(%{ data: %{ project: nil } } = dataset) do
  dataset
end

def validate_project(dataset) do
  validate_required(dataset, :project)
end
```

This is a pattern I typically use for scenarios like this.

**Comment by frekw** [comment]
Sure, there are multiple ways of working around it. I just found the following behaviour to be very unexpected:

```
%{foo: ""} |> Justify.validate_length(:foo, min: 1)
# %Justify.Dataset{data: %{foo: ""}, errors: [], valid?: true}

%{foo: "a"} |> Justify.validate_length(:foo, min: 2)
%Justify.Dataset{
  data: %{foo: "a"},
  errors: [
    foo: {"should be at least %{count} character(s)",
     [count: 2, kind: :min, type: :string, validation: :length]}
  ],
  valid?: false
}
```

because I would have expected both to be invalid.

**Comment by anthonator** [comment]
Sorry it doesn't seem very intuitive. This is how Ecto works as well. I think I agree with their philosophy on the issue. I'm going to close this out. If you'd like to keep discussing feel free.
